name: Release
on:
    push:
        tags:
            - "v**"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Get tag name
                uses: olegtarasov/get-tag@v2.1
                id: tagName
            -   name: Validate semver
                run: |
                    echo $GIT_TAG_NAME | grep -oP '^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
            -   name: Checkout repository
                uses: actions/checkout@v2
            -   name: Validate Gradle wrapper
                uses: gradle/wrapper-validation-action@v1
            -   name: Setup JDK 17
                uses: actions/setup-java@v1
                with:
                    java-version: 17
            -   name: Make Gradle wrapper executable
                if: ${{ runner.os != 'Windows' }}
                run: chmod +x ./gradlew
            -   name: Build and analyze
                run: ./gradlew build codeCoverageReport sonarqube
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                    RELEASE: ${{ steps.tagName.outputs.tag }}
            -   name: Build documentation
                run: ./gradlew allJavadoc
                env:
                    RELEASE: ${{ steps.tagName.outputs.tag }}
            -   name: Publish documentation
                uses: JamesIves/github-pages-deploy-action@4.1.5
                with:
                    branch: gh-pages
                    folder: build/docs/javadoc
            -   name: Publish
                run: ./gradlew publish
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    RELEASE: ${{ steps.tagName.outputs.tag }}
            -   name: Retrieve changelog
                id: changelog_reader
                uses: mindsers/changelog-reader-action@v2
                with:
                    version: 'Unreleased'
                    path: ./CHANGELOG.md
            -   name: Release on GitHub
                uses: softprops/action-gh-release@v1
                id: ghRelease
                with:
                    body: ${{ steps.changelog_reader.outputs.changes }}
                    name: ${{ steps.tagName.outputs.tag }}
                    files: |
                        emberreloaded-*/build/libs/*.jar